blog/urls.py
from django.urls import path

from .import views

app_name = 'blog'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
]

homepage/urls.py
from django.conf.urls import url, include
from .import views

app_name = 'home'
urlpatterns = [
    url('', views.index, name='index'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
#upload
from django.conf import settings
from django.conf.urls.static import static
from homepage.views import index
urlpatterns = [
    path('', index, name='home'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('polls/', include('polls.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
    #path('home/', include('homepage.urls')),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

blog/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField

class BlogPost(models.Model):
    blog_title = models.CharField(max_length = 200)
    blog_text = RichTextUploadingField('contents')
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.blog_title

homepage/models.py
from django.db import models

# Create your models here.

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_feild = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import BlogPost

class IndexView(generic.ListView):
    template_name = 'blog/index.html'
    context_object_name = 'latest_blog_list'
    
    def get_queryset(self):
        return BlogPost.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = BlogPost
    template_name = 'blog/detail.html'
    context_object_name = 'blog'
    
    #def get_queryset(self):
        #return BlogPost.objects.filter(pub_date__lte=timezone.now())

homepage/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'homepage/index.html')

polls/views.py
# Create your views here.
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.db.models import F

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published question."""
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    
    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'
    
    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        #redisplay the question voting form
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes = F('votes') + 1
        #selected_choice.votes += 1 #recing condition, using F() to avoid it.
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Lemon</title>
	{% load static %}
	<link rel="shortcut icon" href="{% static 'homepage/favicon.ico' %}"/>
  </head>

  <body>
   	{% block content %}
	{% endblock %}
	<li><a href={% url 'home' %}>Home</a></li>
  </body>
</html>

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}

{% block content %}
  <h1>{{ blog.blog_title }}</h1>
  <p>{{ blog.pub_date}}</p>
  {% autoescape off %}
  <p>{{ blog.blog_text}}</p>
  {% endautoescape %}
  <li><a href={% url 'blog:index' %}>Return</a></li>
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block content %}
  {% if latest_blog_list %}
    <ul>
    {% for blog in latest_blog_list %}
      <li><a href="{% url 'blog:detail' blog.id %}">{{ blog.blog_title }}</a></li>
	  <p>
	  {{ blog.blog_text|truncatechars:140 }}
	  </p>
    {% endfor %}
    </ul>
  {% else %}
      <p>No blogs are available.</p>
  {% endif %}
{% endblock %}

homepage/templates/homepage/index.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Lemon</title>
	{% load static %}
	<link rel="shortcut icon" href="{% static 'homepage/favicon.ico' %}"/>
  </head>

  <body>
	<h1>This is home page!</h1>
	<li><a href={% url 'blog:index' %}>Blog</a></li>
	<!---
	<li><a href={% url 'polls:index' %}>Polls</a></li>
	--->
  </body>

</html>

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}"
/>

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
		<li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>